#####################

# Vagrantfile starts

####################


VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # config.vm.box = "centos/7"
    config.vm.box = "ubuntu/trusty64"
    config.vm.provider :virtualbox do |v|
        v.memory = 4096
        v.cpus = 4
        v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all", "--ioapic", "on"]
    end

    config.vm.network "private_network", ip: "172.31.128.1", virtualbox__intnet: "innet"
    
    # ssh able
    config.ssh.forward_agent = true

    # add workspace sharing
    if ENV['WORKSPACE']
        config.vm.synced_folder "#{ENV['WORKSPACE']}", "/home/vagrant/src/"
    end

    # Install go-lang
    config.vm.provision :shell, inline: <<-SHELL
       cd /tmp
       curl -LO https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz
       sudo tar -C /usr/local -zxvf go1.8.3.linux-amd64.tar.gz
       echo 'export PATH=$PATH:/usr/local/go/bin' >> /home/vagrant/.bashrc
    SHELL
end
